name: "dbt_profiler"
version: "0.9.0"

require-dbt-version: [">=1.10.0", "<3.0.0"]
config-version: 2

clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
flags:
  require_generic_test_arguments_property: true