name: "dbt_profiler_integration_tests"
version: "0.1.0"
config-version: 2

profile: "integration_tests"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_modules"

seeds:
  +quote_columns: false

models:
  +materialized: table
flags:
  require_generic_test_arguments_property: true