integration_tests:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: '{{ env_var("POSTGRES_HOST") }}'
      user: dbt
      pass: dbt
      port: 5432
      dbname: dbt
      schema: dbt_profiler_integration_tests_postgres
      threads: 1
    bigquery:
      type: bigquery
      method: service-account
      project: '{{ env_var("BIGQUERY_PROJECT") }}'
      dataset: dbt_profiler_integration_tests_bigquery
      location: US
      threads: 4
      keyfile: '{{ env_var("BIGQUERY_KEYFILE") }}'
      timeout_seconds: 300
      priority: interactive
      retries: 1
    sqlserver:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: localhost
      port: 1433
      database: master
      schema: dbt_profiler_integration_tests_sqlserver
      username: sa
      password: "Dbt_profiler_ci_1!"
      authentication: sql
      trust_cert: true
      threads: 1
    snowflake:
      type: snowflake
      account: '{{ env_var("SNOWFLAKE_ACCOUNT") }}'
      user: '{{ env_var("SNOWFLAKE_USER") }}'
      private_key_path: '{{ env_var("SNOWFLAKE_PRIVATE_KEY_PATH") }}'
      role: '{{ env_var("SNOWFLAKE_ROLE") }}'
      database: '{{ env_var("SNOWFLAKE_DATABASE") }}'
      warehouse: '{{ env_var("SNOWFLAKE_WAREHOUSE") }}'
      schema: dbt_profiler_integration_tests_snowflake
      threads: 4