integration_tests:
  target: dev
  outputs:
    dev:
      type: postgres
      host: '{{ env_var("POSTGRES_HOST") }}'
      user: dbt
      pass: dbt
      port: 5432
      dbname: dbt
      schema: integration_tests
      threads: 1