name: continuous-integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ./
  DBT_VERSION: 0.19.1
  INTEGRATION_TEST_RELATION: test_data
  INTEGRATION_TEST_SCHEMA: dbt_profiler_integration_tests_postgres

defaults:
  run:
    working-directory: ./integration_tests

jobs:
  integration_postgres:
    name: integration-postgres
    runs-on: ubuntu-latest
    container: python:3.8-buster
    env:
      POSTGRES_HOST: postgres

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: dbt
          POSTGRES_PASSWORD: dbt
          POSTGRES_DB: dbt
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install dbt==${DBT_VERSION}
          dbt deps
          dbt --version

      - name: Run tests
        run: |
          dbt seed --target postgres
          dbt test --target postgres

      - name: Run print_profile macro
        run: |
          dbt run-operation print_profile --args '{"relation_name": "'$INTEGRATION_TEST_RELATION'", "schema": "'$INTEGRATION_TEST_SCHEMA'"}'

      - name: Run print_profile_schema macro
        run: |
          dbt run-operation print_profile_schema --args '{"relation_name": "'$INTEGRATION_TEST_RELATION'", "schema": "'$INTEGRATION_TEST_SCHEMA'"}'

      - name: Run print_profile_docs
        run: |
          dbt run-operation print_profile_docs --args '{"relation_name": "'$INTEGRATION_TEST_RELATION'", "schema": "'$INTEGRATION_TEST_SCHEMA'"}'

  integration_bigquery:
    name: integration-bigquery
    runs-on: ubuntu-latest
    container: python:3.8-buster
    env:
      BIGQUERY_PROJECT: ${{ secrets.BIGQUERY_PROJECT }}
      BIGQUERY_SERVICE_ACCOUNT_JSON: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_JSON }}
      BIGQUERY_KEYFILE: ./bigquery-service-key.json

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install dbt==${DBT_VERSION}
          dbt deps
          dbt --version

      - name: Test database connection
        run: |
          echo "${BIGQUERY_SERVICE_ACCOUNT_JSON}" > ${BIGQUERY_KEYFILE}
          dbt debug --target bigquery

      - name: Run tests
        run: |
          dbt seed --target bigquery
          dbt test --target bigquery