name: continuous-integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ./
  POSTGRES_HOST: localhost

defaults:
  run:
    working-directory: ./integration_tests

jobs:
  integration_tests:
    name: integration_tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: dbt
          POSTGRES_PASSWORD: dbt
          POSTGRES_DB: dbt

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install dbt==0.19.1
          dbt deps
          dbt --version

      - name: Run seeds
        run: dbt seed