name: continuous-integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ./integration_tests

defaults:
  run:
    working-directory: ./integration_tests

jobs:
  integration_tests:
    name: integration_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install dbt==0.19.1
          dbt deps
          dbt --version